FROM docksal/cli:1.3-php7

MAINTAINER James Glasgow <james@jrglasgow.com>

RUN apt-get update && \
  apt-get install libsodium-dev -y && \
  apt-get -y --force-yes --no-install-recommends install php-pear libssl-dev php7.0-dev && \
  pecl channel-update pecl.php.net && \
  pecl install libsodium-1.0.6 && \
  echo "extension=libsodium.so" > /etc/php/7.0/fpm/php.ini  &&\
  echo "extension=libsodium.so" > /etc/php/7.0/cli/php.ini

RUN DEBIAN_FRONTEND=noninteractive apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*