#!/bin/bash

## enable development modules
##
## Usage: fin develop.sh
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
SQL_BACKUP_PATH="${PROJECT_ROOT}/.docksal/db"
DEVELOP_SCRIPT="${PROJECT_ROOT}/.docksal/commands/develop"
START_DIRECTORY=`pwd`

echo "DOCROOT_PATH: $DOCROOT_PATH"
#cd $DOCROOT_PATH

#echo "";
#echo "";
#echo "Clear Caches"
#fin drush cr

#echo "";
#echo "";
#echo "Disable Syslog and Autologout modules"
#fin drush dis syslog autologout -y

#echo "";
#echo "";
#echo "Enable development modules"
#fin drush en devel search_krumo dblog views_ui context_ui stage_file_proxy diff mail_redirect update xhprof missing_module -y;

echo ""
echo ""
echo "Run database updates"
fin drush updb -y

cd $START_DIRECTORY
