#!/bin/bash

## enable development modules
##
## Usage: fin develop.sh
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
SQL_BACKUP_PATH="${PROJECT_ROOT}/.docksal/db"
DEVELOP_SCRIPT="${PROJECT_ROOT}/.docksal/commands/develop"
START_DIRECTORY=`pwd`
DEVELOP_LOCAL_SCRIPT='develop.local.sh'

echo "DOCROOT_PATH: $DOCROOT_PATH"
#cd $DOCROOT_PATH

echo "";
echo "";
echo "Clear module list";
fin drush cc module-list

echo "";
echo "";
echo "Rebuild Registry"
fin drush rr

echo "";
echo "";
echo "Disable Syslog and Autologout modules"
fin drush dis syslog autologout -y

echo "";
echo "";
echo "Enable development modules"
fin drush en devel search_krumo dblog views_ui context_ui stage_file_proxy diff mail_redirect update xhprof missing_module -y;
fin drush dl documentation
echo ""
echo ""
echo "Run database updates"
fin drush updb -y

fin drush dl utf8mb4_convert -y
fin drush utf8mb4-convert-databases -y

if [ -f $DEVELOP_LOCAL_SCRIPT ]
then
  echo ""
  echo -e "${green_bg} Step 4 ${NC}${green} Running Local Development script...${NC}"
  bash $DEVELOP_LOCAL_SCRIPT
fi

cd $START_DIRECTORY
