#!/usr/bin/env bash

## Set drush aliases
##
## Usage: fin drush-alias
echo "execute the following command or add it to your .bash_rc file"
echo "alias drush='fin drush -i /var/www/.docksal/drush_commands'"
