#!/usr/bin/env bash

## Initialize a Docksal powered Drupal 7 site
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
SQL_BACKUP_PATH="${PROJECT_ROOT}/.docksal/db"
DEVELOP_SCRIPT="${PROJECT_ROOT}/.docksal/commands/develop"
echo "VIRTUAL_HOST: ${VIRTUAL_HOST} - 20"
#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
yellow_bg='\033[43m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

is_windows ()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

is_mac ()
{
	local res=$(uname | grep 'Darwin')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"
	
	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo-yellow "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings ()
{
  #check to ensure settings.local.php exists
  if [ ! -f "${SITEDIR_PATH}/settings.local.php" ]
  then
    copy_settings_file "${PROJECT_ROOT}/.docksal/example.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
  fi

  #check to ensure settings.php exists
  if [ ! -f "${SITEDIR_PATH}/settings.php" ]
  then
    copy_settings_file "${SITEDIR_PATH}/default.settings.php" "${SITEDIR_PATH}/settings.php"
  fi

  echo "checking ${SITEDIR_PATH}/settings.php"
  # ensure settings.local.php is getting loaded
  if [[ ! -n $(grep "require($local_conf_file_path);" "${SITEDIR_PATH}/settings.php") ]]
  then
    SETTINGS_FILE="${SITEDIR_PATH}/settings.php"
    # make the file writable
    chmod 775 $SETTINGS_FILE
    echo "
// Load local settings file if it exists.
\$local_conf_file_path = __DIR__ . '/settings.local.php';
if (file_exists(\$local_conf_file_path)) {
  require(\$local_conf_file_path);
}" >> $SETTINGS_FILE
    # make the file not writable
    chmod 555 $SETTINGS_FILE
  fi

  echo ""
}

# Fix file/folder permissions
fix_permissions ()
{
	echo-green "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	# We disable email sending here so site-install does not return an error
	fin exec "PHP_OPTIONS="'"-d sendmail_path=`which true`"'" drush site-install -y --site-name='My Drupal 7 Site'"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set"
	exit 1
fi

if [ ! -d $SQL_BACKUP_PATH ]
then
  echo "Cannot continue, backup file cannot be located. Please put backup file or symlink at $SQL_BACKUP_PATH"
  exit 1
fi

# Project initialization steps
echo -e "${green_bg} Step 1 ${NC}${green} Initializing local project configuration...${NC}"
fix_permissions
init_settings

if [[ $DOCKER_RUNNING == "true" ]]; then
	echo -e "${green_bg} Step 2 ${NC}${green} Recreating services...${NC}"
	fin reset -f
else
	echo -e "${green_bg} Step 2 ${NC}${green} Creating services...${NC}"
	fin up
fi

echo "Waiting 10s for MySQL to initialize...";
sleep 10

#echo -e "${green_bg} Step 3 ${NC}${green} Installing site...${NC}"
#time site_install

echo ""
echo -e "${green_bg} Step 3 ${NC}${green} Restoring backup...${NC}"
for f in $SQL_BACKUP_PATH/*.sql.gz
do
  echo -e "${yellow_bg} Importing ${NC}${yellow} $f ...${NC}"
    case "$f" in
      *.sh)     bash $f;;
      *.sql)    echo "UPDATE users_field_data SET mail=CONCAT('local_dev-', uid, '@${VIRTUAL_HOST}') WHERE uid <> 0;" | (pv $f && cat) |  fin db import; echo;;
      *.sql.gz) echo "UPDATE users_field_data SET mail=CONCAT('local_dev-', uid, '@${VIRTUAL_HOST}') WHERE uid <> 0;" | (pv $f | gunzip && cat) |  fin db import; echo;;
      *)        echo "$0: ignoring $f" ;;
    esac


done

if [ -f $DEVELOP_SCRIPT ]
then
  echo ""
  echo -e "${green_bg} Step 4 ${NC}${green} Running Development script...${NC}"
  bash $DEVELOP_SCRIPT
fi


if is_windows; then
	echo-green "Add ${VIRTUAL_HOST} to your hosts file (/etc/hosts), e.g.:"
	echo-green "${VM_IP} ${VIRTUAL_HOST}"
	echo
fi



echo -en "${green_bg} DONE! ${NC} "
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
MYSQL_HOST_PORT=`fin config env | grep MYSQL | cut -d " " -f 2`
echo -e "MySQL server can be accessed at ${yellow}${MYSQL_HOST_PORT}${NC}"
if is_mac; then
	open "http://${VIRTUAL_HOST}"
fi


#-------------------------- END: Execution --------------------------------
