#!/bin/bash

## Log the user into Drupal
##
## Usage: fin login <username>
## The user defined in $USER_LOGIN in docksal-local.env will be logged in, if a
## username is passed as a parameter that user will be logged in instead, if
## neither are available the superuser will be logged in.

is_mac ()
{
	local res=$(uname | grep 'Darwin')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

PWD=`pwd`

ABSOLUTE_DOCROOT=$PROJECT_ROOT/$DOCROOT/

cd $ABSOLUTE_DOCROOT

# are there arguments passed to this script?
if [ ! "$#" -eq "0" ];
then
  COMMAND="fin drush uli ${@}"
else
  echo "no arguments were passed in"
  if [ $USER_LOGIN ];
  then
    COMMAND="fin drush uli ${USER_LOGIN}"
  else
    COMMAND="fin drush uli"
  fi
fi

# make sure we trim the carriage return if is appears
LOGIN_URL=`$COMMAND | tr -d '\r'`
echo $LOGIN_URL

if is_mac; then
  open $LOGIN_URL
fi

cd $PWD
